version: '3'
services:
  connector-security-affairs:
    image: unics/connector-security-affairs:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=SecurityAffairs
      - CONNECTOR_SCOPE=Bundle, Malware, Report, Note, Relationship, Identity, ExternalReference # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - SECURITYAFFAIRS_INTERVAL=2
    restart: always
